[2022-01-14 20:52:03,095] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks scheduled__2022-01-13T00:00:00+00:00 [queued]>
[2022-01-14 20:52:03,450] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks scheduled__2022-01-13T00:00:00+00:00 [queued]>
[2022-01-14 20:52:03,453] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 20:52:03,453] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-14 20:52:03,453] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 20:52:04,948] {taskinstance.py:1259} INFO - Executing <Task(SubDagOperator): processing_tasks> on 2022-01-13 00:00:00+00:00
[2022-01-14 20:52:05,447] {standard_task_runner.py:52} INFO - Started process 49099 to run task
[2022-01-14 20:52:06,249] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'processing_tasks', 'scheduled__2022-01-13T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmp9mbyj1c1', '--error-file', '/tmp/tmp869ueah4']
[2022-01-14 20:52:07,494] {standard_task_runner.py:77} INFO - Job 61: Subtask processing_tasks
[2022-01-14 20:52:14,603] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.processing_tasks scheduled__2022-01-13T00:00:00+00:00 [running]> on host airflowvm
[2022-01-14 20:52:19,890] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=processing_tasks
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-13T00:00:00+00:00
[2022-01-14 20:52:19,904] {logging_mixin.py:109} WARNING - /home/airflow/sandbox/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-01-14 20:52:23,341] {subdag.py:176} INFO - Created DagRun: scheduled__2022-01-13T00:00:00+00:00
[2022-01-14 20:53:25,291] {base.py:249} INFO - Success criteria met. Exiting.
[2022-01-14 20:53:26,186] {subdag.py:191} INFO - Execution finished. State is success
[2022-01-14 20:53:27,191] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=processing_tasks, execution_date=20220113T000000, start_date=20220114T205203, end_date=20220114T205327
[2022-01-14 20:53:28,288] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-14 20:53:31,846] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
