[2022-03-15 19:15:30,008] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks scheduled__2022-03-14T00:00:00+00:00 [queued]>
[2022-03-15 19:15:30,052] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_tasks scheduled__2022-03-14T00:00:00+00:00 [queued]>
[2022-03-15 19:15:30,054] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 19:15:30,055] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-03-15 19:15:30,055] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 19:15:30,112] {taskinstance.py:1259} INFO - Executing <Task(SubDagOperator): processing_tasks> on 2022-03-14 00:00:00+00:00
[2022-03-15 19:15:30,132] {standard_task_runner.py:52} INFO - Started process 3694 to run task
[2022-03-15 19:15:30,137] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'processing_tasks', 'scheduled__2022-03-14T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmp75j3kg_k', '--error-file', '/tmp/tmpx_9_42ta']
[2022-03-15 19:15:30,152] {standard_task_runner.py:77} INFO - Job 133: Subtask processing_tasks
[2022-03-15 19:15:31,283] {logging_mixin.py:109} INFO - Running <TaskInstance: parallel_dag.processing_tasks scheduled__2022-03-14T00:00:00+00:00 [running]> on host airflowvm
[2022-03-15 19:15:32,916] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=processing_tasks
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T00:00:00+00:00
[2022-03-15 19:15:33,134] {logging_mixin.py:109} WARNING - /home/airflow/sandbox/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-15 19:15:33,745] {subdag.py:176} INFO - Created DagRun: scheduled__2022-03-14T00:00:00+00:00
[2022-03-15 19:16:34,033] {base.py:249} INFO - Success criteria met. Exiting.
[2022-03-15 19:16:34,141] {subdag.py:191} INFO - Execution finished. State is success
[2022-03-15 19:16:34,255] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=processing_tasks, execution_date=20220314T000000, start_date=20220315T191530, end_date=20220315T191634
[2022-03-15 19:16:34,383] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-15 19:16:34,887] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
